version: '3'

services:
  php:
    container_name: continuous_integration_app_php
    build: ./docker/php
    volumes:
      - ./www:/var/www
    links:
      - redis
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    container_name: continuous_integration_nginx
    ports:
      - 8082:80
    volumes:
      - ./www/public:/var/www/public
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:5.7
    container_name: nda_app_mysqld
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      #- ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      #- ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: continuous_integration
      MYSQL_USER: continuous_integration_user
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'

  redis:
    container_name: continuous_integration_redis
    image: redis:latest
